volumes:
  rindus_postgres_data: {}

services:
  postgres:
    restart: always
    container_name: rindus_postgres
    image: postgres:16
    env_file:
      - ./.envs/postgres
    volumes:
      - rindus_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  django:
    container_name: rindus_django
    build:
      context: .
      dockerfile: DockerFile
    env_file:
      - ./.envs/django
      - ./.envs/postgres
    entrypoint: /entrypoint.sh
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - rindus_postgres_data:/var/lib/postgresql/data
      - .:/app:z
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
