# Generated by Django 4.2.11 on 2024-05-07 13:18

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="comment",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="post",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[
                    ("S", "Synced"),
                    ("C", "Created"),
                    ("U", "Updated"),
                    ("D", "Deleted"),
                ],
                default="C",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("S", "Synced"),
                    ("C", "Created"),
                    ("U", "Updated"),
                    ("D", "Deleted"),
                ],
                default="C",
                max_length=1,
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["status"], name="comment_sync_status_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["status"], name="post_sync_status_idx"),
        ),
    ]
