# Generated by Django 4.2.11 on 2024-05-08 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_comment_managers_alter_post_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="comment",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="post",
            managers=[],
        ),
    ]
